Algoritmo "EX24 L02"

// Exercício24:
//    Solicitar o nome e a idade de 3 pessoas (utilizando a estrutura PARA).

Var
   c, id: inteiro
   nome: caractere

Inicio
      c <- 1
      
      para c de 1 ate 3 faca
         escreva("Digite o nome da ", c, "º pessoa: ")
         leia(nome)
         escreva("Digite a idade da ", c, "º pessoa: ")
         leia(id)
         escreval
      fimpara

Fimalgoritmo