Algoritmo "EX23 L02"

// Exercício 23:
//    Solicitar o nome e a idade de 3 pessoas (utilizando a estrutura FAÇA...ENQUANTO).

Var
   c, id: inteiro
   nome: caractere

Inicio
      c <- 1

      enquanto (c < 4)faca
         escreva("Digite o nome da ", c, "º pessoa: ")
         leia(nome)
         escreva("Digite a idade da ", c, "º pessoa: ")
         leia(id)
         escreval
         c <- c + 1
      fimenquanto

Fimalgoritmo