Algoritmo "EX18 L01"

// Exercício 18:
//    Solicite um número inteiro e apresente o resto da divisão por 2
//    (usar operador MOD ou %)

Var
   N: inteiro

Inicio
      escreva(" Digite um número inteiro: ")
      leia(N)
      escreval
      escreval("           ", N, "  |_2_")
      escreval("                 ", N/2)
      escreval
      escreval("        -> ", N%2, " <-")
      escreval
      escreval(" O resto da divisão de ", N, " por 2 é igual a ", N%2)

Fimalgoritmo