Algoritmo "EX15 L01"

// Exercício 15:
//    Faça o mesmo exercício anterior sem utilizar uma terceira variável

Var
   N1, N2: real

Inicio
      escreval
      escreval("      (N1 - N2) / 10 ")
      escreval
      escreva(" Digite o 1° número(N1): ")
      leia(N1)
      escreva(" Digite o 2º número(N2): ")
      leia(N2)
      escreval(" --------------------------")
      escreval(" (", N1, " - ", N2, ") / 10 = ", (N1 - N2)/10:6:2)

Fimalgoritmo