Algoritmo "EX24 L01"

// Exercício 24:
//    Solicite dois valores e apresente a soma com acréscimo de 18%

Var
   v1, v2, ac: real

Inicio
      escreval(" SOMA DE 2 VALORES COM ACRÉSCIMO DE 18%")
      escreval
      escreva(" Digite o 1° valor: ")
      leia(v1)
      escreva(" Digite o 2° valor: ")
      leia(v2)
      ac <- 0.18*(v1+v2)
      escreval
      escreval(" RESULTADO: ", V1+V2+ac:6:2)

Fimalgoritmo