Algoritmo "Ex02 L01"

// Exercício 02:
//    Leia duas variáveis numéricas e apresente a soma entre elas,
//    podendo ou não armazenar o resultado em uma terceira variável.

Var
   N1, N2: inteiro

Inicio
      escreval ("------ SOMA ENTRE DOIS NÚMEROS ------")
      escreval
      escreva("Digite o primeiro número: ")
      leia (N1)
      escreva("Digite o segundo número:  ")
      leia (N2)
      escreval
      escreval("     ",N1, " + ", N2, " = ", N1 + N2)
      
Fimalgoritmo