Algoritmo "EX13 L01"

// Exercício 13:
//    Leia 3 números e calcule: (primeiro número + terceiro número) * segundo número

Var
   N1, N2, N3: inteiro

Inicio
      escreval("_____|(N1 + N3) x N2|_____")
      escreval
      escreva(" Digite o 1º número(N1): ")
      leia(N1)
      escreva(" Digite o 2º número(N2): ")
      leia(N2)
      escreva(" Digite o 3º número(N3): ")
      leia(N3)
      escreval
      escreval(" (", N1, " + ", N3, ") x ", N2, " = ", (N1 + N3)*N2)
Fimalgoritmo