Algoritmo "EX11 L01"

// Exercício 11:
//    Leia 3 notas e calcule a média aritmética

Var
   N1, N2,N3: real

Inicio
      escreval(" --------- NOTAS ---------")
      escreval
      escreva(" Digite a 1ª nota: ")
      leia(N1)
      escreva(" Digite a 2ª nota: ")
      leia(N2)
      escreva(" Digite a 3ª nota: ")
      leia(N3)
      escreval
      escrevaL(" MÉDIA: ", (N1 + N2 + N3)/3 :5:1)

Fimalgoritmo