Algoritmo "EX16 L01"

// Exercício 16
//    Leia 5 números fornecidos pelo usuário e calcule a soma total

Var
   N1, N2, N3, N4, N5: inteiro

Inicio
      escreval("--- SOMA DE 5 NÚMEROS ---")
      escreval
      escreva(" Digite o 1º número: ")
      leia(N1)
      escreva(" Digite o 2º número: ")
      leia(N2)
      escreva(" Digite o 3º número: ")
      leia(N3)
      escreva(" Digite o 4º número: ")
      leia(N4)
      escreva(" Digite o 5º número: ")
      leia(N5)
      escreval
      escreval(" A soma dos números é ", N1 + N2 + N3 + N4 + N5)

Fimalgoritmo