Algoritmo "EX12 L01"

// Exercício 12:
//    Leia 3 números inteiros e calcule a multiplicação entre eles

Var
   N1, N2, N3: inteiro
   
Inicio
      escreval("---- MULTIPLICAÇÃO ENTRE 3 NÚMEROS ----")
      escreval
      escreva(" Digite o 1º número: ")
      leia(N1)
      escreva(" Digite o 2º número: ")
      leia(N2)
      escreva(" Digite o 3º número: ")
      leia(N3)
      escreval
      escreval(" ",N1, " x ", N2, " x ", N3, " = ", N1 * N2 * N3)

Fimalgoritmo